#!/usr/bin/env node
/**
 * Bump the OpenBiliClaw version everywhere at once.
 *
 * The same SemVer lives in four places that historically drift:
 *
 *   1. extension/package.json                       (npm metadata)
 *   2. extension/manifest.json                      (canonical for the
 *                                                    WebExtension; build.mjs
 *                                                    injects this into the
 *                                                    safari/firefox output
 *                                                    manifests)
 *   3. safari/project.yml MARKETING_VERSION         (XcodeGen spec)
 *   4. safari/OpenBiliClawSafari.xcodeproj/project.pbxproj
 *      MARKETING_VERSION lines                      (committed xcodeproj —
 *                                                    normally regenerated by
 *                                                    xcodegen, but the file
 *                                                    is in version control,
 *                                                    so we keep it in sync
 *                                                    even without xcodegen
 *                                                    installed)
 *
 * Usage:
 *   node scripts/bump-version.mjs <new-version>     # explicit
 *   node scripts/bump-version.mjs patch             # 0.3.44 → 0.3.45
 *   node scripts/bump-version.mjs minor             # 0.3.44 → 0.4.0
 *   node scripts/bump-version.mjs major             # 0.3.44 → 1.0.0
 *   node scripts/bump-version.mjs --check           # verify all four agree
 *
 * Refuses to run if the version is not strictly increasing (npm publish
 * etc. don't accept downgrades).
 *
 * After bumping, the script reminds you to:
 *   - rerun `npm run build` (rewrites the firefox/safari manifests)
 *   - rerun `xcodegen generate` from safari/ (only if you've changed
 *     project.yml in a way other than MARKETING_VERSION; for a pure
 *     version bump the script already patched project.pbxproj too)
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const repoRoot = resolve(root, "..");

const SEMVER = /^(\d+)\.(\d+)\.(\d+)(?:-[\w.-]+)?(?:\+[\w.-]+)?$/;

const FILES = [
  {
    label: "extension/package.json",
    path: resolve(root, "package.json"),
    kind: "json",
    key: "version",
  },
  {
    label: "extension/manifest.json",
    path: resolve(root, "manifest.json"),
    kind: "json",
    key: "version",
  },
  {
    label: "safari/project.yml MARKETING_VERSION",
    path: resolve(repoRoot, "safari", "project.yml"),
    kind: "yaml-marketing-version",
  },
  {
    label: "safari/.../project.pbxproj MARKETING_VERSION",
    path: resolve(repoRoot, "safari", "OpenBiliClawSafari.xcodeproj", "project.pbxproj"),
    kind: "pbxproj-marketing-version",
  },
];

// ── Readers ─────────────────────────────────────────────────────────

async function readVersion(file) {
  const text = await readFile(file.path, "utf-8");
  switch (file.kind) {
    case "json": {
      const obj = JSON.parse(text);
      const v = obj[file.key];
      if (typeof v !== "string") {
        throw new Error(`${file.label}: missing or non-string \`${file.key}\``);
      }
      return v;
    }
    case "yaml-marketing-version": {
      // Match the exact YAML key line. We don't want to pull in a real
      // YAML parser for a single key.
      const m = text.match(/^(\s*)MARKETING_VERSION:\s*"?([0-9.\w+-]+)"?\s*$/m);
      if (!m) throw new Error(`${file.label}: MARKETING_VERSION not found`);
      return m[2];
    }
    case "pbxproj-marketing-version": {
      // pbxproj uses `MARKETING_VERSION = 0.3.44;`. There can be multiple
      // (one per build configuration × target). They should all agree.
      const matches = [...text.matchAll(/MARKETING_VERSION = ([0-9.\w+-]+);/g)];
      if (matches.length === 0) {
        throw new Error(`${file.label}: no MARKETING_VERSION entries found`);
      }
      const versions = new Set(matches.map(m => m[1]));
      if (versions.size > 1) {
        throw new Error(
          `${file.label}: inconsistent versions across configurations: ${[...versions].join(", ")}`,
        );
      }
      return [...versions][0];
    }
    default:
      throw new Error(`unknown file kind: ${file.kind}`);
  }
}

// ── Writers ─────────────────────────────────────────────────────────

async function writeVersion(file, newVersion) {
  const text = await readFile(file.path, "utf-8");
  let out;
  switch (file.kind) {
    case "json": {
      // We preserve the existing formatting by doing a targeted
      // string replace rather than re-serializing — both files use
      // 2-space indent and JSON.stringify with 2-space matches that,
      // but a tab-indented version-only edit avoids surprising the
      // user with churn on unrelated lines.
      const obj = JSON.parse(text);
      const old = JSON.stringify(obj[file.key]);
      const replacement = JSON.stringify(newVersion);
      // Replace the first occurrence on a line that looks like
      //     "version": "0.3.44"
      const re = new RegExp(`("${file.key}"\\s*:\\s*)${escapeRegex(old)}`);
      if (!re.test(text)) {
        throw new Error(`${file.label}: couldn't locate \`${file.key}\` for in-place edit`);
      }
      out = text.replace(re, `$1${replacement}`);
      break;
    }
    case "yaml-marketing-version": {
      out = text.replace(
        /^(\s*MARKETING_VERSION:\s*"?)[0-9.\w+-]+("?\s*)$/m,
        `$1${newVersion}$2`,
      );
      if (out === text) {
        throw new Error(`${file.label}: MARKETING_VERSION not found to replace`);
      }
      break;
    }
    case "pbxproj-marketing-version": {
      out = text.replaceAll(
        /MARKETING_VERSION = [0-9.\w+-]+;/g,
        `MARKETING_VERSION = ${newVersion};`,
      );
      if (out === text) {
        throw new Error(`${file.label}: no MARKETING_VERSION lines to replace`);
      }
      break;
    }
    default:
      throw new Error(`unknown file kind: ${file.kind}`);
  }
  await writeFile(file.path, out);
}

// ── Helpers ─────────────────────────────────────────────────────────

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function parseSemver(v) {
  const m = SEMVER.exec(v);
  if (!m) throw new Error(`not a valid SemVer: ${v}`);
  return { major: +m[1], minor: +m[2], patch: +m[3] };
}

function cmp(a, b) {
  const av = parseSemver(a);
  const bv = parseSemver(b);
  if (av.major !== bv.major) return av.major - bv.major;
  if (av.minor !== bv.minor) return av.minor - bv.minor;
  return av.patch - bv.patch;
}

function bump(current, kind) {
  const v = parseSemver(current);
  switch (kind) {
    case "major": return `${v.major + 1}.0.0`;
    case "minor": return `${v.major}.${v.minor + 1}.0`;
    case "patch": return `${v.major}.${v.minor}.${v.patch + 1}`;
    default: throw new Error(`unknown bump kind: ${kind}`);
  }
}

// ── Main ────────────────────────────────────────────────────────────

async function main() {
  const arg = process.argv[2];
  if (!arg) {
    console.error("usage: bump-version.mjs <version|patch|minor|major|--check>");
    process.exit(2);
  }

  // Read all current versions first.
  const current = await Promise.all(
    FILES.map(async f => ({ file: f, version: await readVersion(f) })),
  );

  console.log("Current versions:");
  for (const { file, version } of current) {
    console.log(`  ${file.label.padEnd(48)} ${version}`);
  }

  // --check just verifies they agree.
  if (arg === "--check") {
    const unique = new Set(current.map(c => c.version));
    if (unique.size === 1) {
      console.log(`\n✓ all four locations agree on ${[...unique][0]}`);
      process.exit(0);
    } else {
      console.error(`\n✗ versions disagree: ${[...unique].join(", ")}`);
      process.exit(1);
    }
  }

  // Canonical version is extension/manifest.json (build.mjs treats it
  // as the source of truth for the bundled manifest output).
  const canonical = current.find(c => c.file.path.endsWith("manifest.json")).version;

  let next;
  if (["patch", "minor", "major"].includes(arg)) {
    next = bump(canonical, arg);
  } else {
    next = arg;
    // Validate.
    parseSemver(next);
  }

  if (cmp(next, canonical) <= 0) {
    console.error(`\n✗ refusing to bump: ${next} ≤ canonical ${canonical}`);
    process.exit(1);
  }

  console.log(`\nBumping to ${next}…`);
  for (const { file } of current) {
    await writeVersion(file, next);
    console.log(`  ✓ ${file.label}`);
  }

  console.log(`\nDone. Next steps:`);
  console.log(`  1. (if changing extension code) cd extension && npm run build`);
  console.log(`  2. (safari)                     cd extension && npm run package:safari`);
  console.log(`  3. (only if project.yml has other changes) cd safari && xcodegen generate`);
  console.log(`  4. git diff to review, then commit.`);
}

main().catch(err => {
  console.error(`\n✗ ${err.message}`);
  process.exit(1);
});
