/**
 * Message protocol between popup-launcher.{html,js} and the
 * background service worker.
 *
 * This module is the single source of truth for the message-type
 * strings. The popup-launcher.js side reads the same constants from
 * the generated mirror at `extension/popup/popup-launcher-protocol.js`
 * (generated by `scripts/sync-launcher-protocol.mjs` so the two stay
 * in lockstep). If you edit this file, run that script (or just rerun
 * `npm run build`, which invokes it transparently).
 *
 * Why a separate file: popup-launcher.js is NOT a bundled esbuild
 * entrypoint — it's a plain-JS file copied verbatim into the safari
 * bundle. We don't want to make it a TS entrypoint (would force every
 * call site through the bundler and re-jig the asset copy logic), but
 * we also don't want the string typed twice and slowly drifting.
 * The generated mirror is the compromise.
 */

/** Sent by the popup launcher to confirm the background SW is alive. */
export const PING_LAUNCHER_TO_BG = "openbiliclaw/popup-launcher/ping";

/**
 * Sent by the popup launcher to ask "is the current foreground tab
 * a bilibili video that the backend has flagged as a YT repost?"
 *
 * Reply shape: see `LauncherPendingStatus`.
 */
export const QUERY_LAUNCHER_PENDING_STATUS =
  "openbiliclaw/popup-launcher/query-pending";

/** Reply to a PING. The SW echoes its version so a corrupt or stale
 * worker can be spotted from the popup. */
export interface PingReply {
  ok: true;
  sw_version: string;
}

/** Reply to a pending-status query. All fields optional so the popup
 * can render whatever's available. */
export interface LauncherPendingStatus {
  /** True when the current B站 video has been flagged as a YT repost. */
  isRepost: boolean;
  /** True when isRepost is true but the YT URL isn't known (server
   * couldn't reach YouTube yet — the "pending" state from the
   * yt-replacer lookup). */
  isPending: boolean;
  /** The YT URL if we have it, otherwise empty. */
  ytUrl: string;
}

/** Union of every message type this protocol carries. Used by the
 * SW's onMessage dispatch so the switch is exhaustive. */
export type LauncherMessage =
  | { type: typeof PING_LAUNCHER_TO_BG }
  | { type: typeof QUERY_LAUNCHER_PENDING_STATUS };
